var express = require('express');
var request = require('request');
var app = express();

app.use(express.static(__dirname + '/public'));

app.get('/ajaxcall', function(req, res){
	// var data = {  
	// 	isToday:false,
	// 	launchDate:{  
	// 		zh_HK: "2017 å¹´ 9 æœˆ 22 æ—¥æ˜ŸæœŸäº",
	// 		en_HK: "Friday, September 22, 2017",
	// 	},
	// 	updated:1505642760009,
	// 	stores:{  
	// 		R499:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 					// contract:Math.random() >= 0.5,
	// 					// unlocked:Math.random() >= 0.5
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		},
	// 		R610:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		},
	// 		R673:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		},
	// 		R485:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		},
	// 		R409:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		},
	// 		R428:{  
	// 			"MQ6L2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8E2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8J2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7G2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6K2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ6M2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ7F2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8D2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			},
	// 			"MQ8H2ZP/A":{  
	// 				availability:{  
	// 					contract:false,
	// 					unlocked:false
	// 				}
	// 			}
	// 		}
	// 	}
	// };

	// res.send(data);

	var url = "https://reserve-prime.apple.com/HK/en_HK/reserve/iPhone/availability.json";
	request({
		url: url,
		json: true
	}, function (error, response, body) {
		if (!error && response.statusCode === 200) {
	    	var json  = JSON.stringify(body);
    		res.send(json);
	    } else {
	    	res.send(error);
	    }
	})


});

app.listen(8000);